(function(){ovi.provide("nokia.maps.heatmap._StackBlur");
(nokia.maps.heatmap.bs=function(){}).prototype={blurContext:function(e,k,h,d,c,g,b,f){e=this.blurData(e.getImageData(d,c,g,b),h,g,b,f||15);k.putImageData(e,d,c)},blurData:function(e,k,h,d,c){this.blurArray(e.data,k,h,d,c);return e},blurArray:function(e,k,h,d,c){c&1&&this.convolve(e,e,k,h,d,0);c&2&&this.convolve(e,e,k,h,d,1);c&4&&this.convolve(e,e,k,h,d,2);c&8&&this.convolve(e,e,k,h,d,3);return e},convolve:function(e,k,h,d,c,g){var b=(h+1)*(h+1),f,q,a,r,l,m,p,z,s,v=d*4,u=h+1,x,w=[{r:0,g:0,b:0,a:0,
next:null}];p=1;var y=["r","g","b","a"][g];a=2*h+1;for(var B,D,A;p<a;p++)w[p]={r:0,g:0,b:0,a:0,next:null},w[p-1].next=w[p];w[2*h].next=w[0];D=(d-1)*4;for(q=0;q<c;q++){m=q*v;f=e[m+g];l=f*u*(h+2)/2;a=f*u;for(p=0;p<=h;p++)w[p][y]=f;r=0;for(p=1;p<=h;p++)z=p<d?m+p*4:m+D,z=e[z+g],l+=z*(u-p),r+=z,w[h+p][y]=z;z=w[0];B=w[u];p=m;A=u*4;rowEnd=m+D;for(f=0;f<d;f++)if(k[p+g]=l/b,l-=a,s=f+u<d?p+A:rowEnd,s=e[s+g],r+=s,l+=r,a-=z[y],a+=B[y],r-=B[y],z[y]=s,z=z.next,B=B.next,p+=4,!l)for(;(x=(f+u)*4)<v&&e[m+g+x]==0;)f++,
p+=4}m=(c-1)*v;for(f=0;f<d;f++){e=f*4;q=k[e+g];l=q*u*(h+2)/2;a=q*u;for(p=0;p<=h;p++)w[p][y]=q;r=0;for(p=1;p<=h;p++)z=p<c?e+p*v:e+m,z=k[z+g],l+=z*(h-p+1),r+=z,w[h+p][y]=z;z=w[0];B=w[u];p=e;D=u*v;colEnd=e+m;for(q=0;q<c;q++)if(k[p+g]=l/b,l-=a,s=q+u<c?p+D:colEnd,s=k[s+g],r+=s,l+=r,a-=z[y],a+=B[y],r-=B[y],z[y]=s,z=z.next,B=B.next,p+=v,!l)for(;(x=q+u)<c&&k[x*v+g+e]==0;)q++,p+=v}}};ovi.provide("nokia.maps.heatmap._TileRenderer");
(function(e){function k(b,a){return b.stop-a.stop}var h=Math,d=h.floor,c=h.log,g=e.heatmap,b=e.util,f=b.d;g.ds=ovi.Class({Statics:{DEFAULT_COLORS:{stops:{0:"#008","0.2":"#0b0","0.5":"#ff0","0.7":"#f00"},interpolate:!0}},initialize:function(d,a,e){d>>=a;this.lw=a;this.Yt=d;this.mu=c(d)/c(2);this.ws=a=document.createElement("canvas");this.xs=a.getContext("2d");this.ys=a.width=a.height=d*3;this.Io=new g.bs;var l=document.createElement("canvas"),h,a=e.interpolate,p=e.stops,d=[],z,s,v;l.width=256;l.height=
1;l=l.getContext("2d");for(h in p)p.hasOwnProperty(h)&&d.push({stop:parseFloat(h),value:p[h]});p=d.length;p<2&&b.d("The heat map colors definition must have at least two values.");d.sort(k);d[0].stop>0&&d.unshift({stop:0,value:d[0].value});d[p-1].stop<1&&d.push({stop:1,value:d[p-1].value});p=d.length;h=l.createLinearGradient(0,0,256,0);for(z=0;z<p;z++)isNaN(d[z].stop)&&f("Stop offset for heat map color definitions must be parseable floats."),!a&&s&&(v=s.stop+(d[z].stop-s.stop)/2,h.addColorStop(v,
s.value),h.addColorStop(v,d[z].value)),h.addColorStop(d[z].stop,d[z].value),s=d[z];l.fillStyle=h;l.fillRect(0,0,256,1);this.Js=l.getImageData(0,0,256,1).data;this.Zt=e.interpolate},paint:function(b,a,c,f,g,e,k,s,v){var a=this.Yt,f=this.xs,u,x=e==="density"?2:1,w=x,c=h.min(c+x,this.mu),y,B,D,A,C,x=this.ys,E;g&&e==="value"?this.Pu(b,k,s,v,f,a,x):(f.fillStyle=g?"#080":"#000",f.fillRect(0,0,x,x));for(;w<=c&&k+w<=b.Ya;w++){A=a>>w;offset=a-A;E=e==="density"?127+d(128/(1<<c-w)):255;C=(1<<w)+2;g=this.Ct(b,
w,k,s,v,!1);for(y=g.length;y--;)if(B=y%C,D=y/C<<0,u=g[y])u=b.Kj(u.average),f.fillStyle="rgba("+u+","+E+",0,1)",f.fillRect(B*A+offset,D*A+offset,A,A);this.Io.blurContext(f,f,A,offset,offset,a+2*A,a+2*A,3)}b=this.Ks(f.getImageData(0,0,x,x),this.Js,this.Zt);f.putImageData(b,0,0);return[this.ws,a]},Ks:function(b,a,c){for(var f=b.data,d,g,e=0,h=f.length;e<h;e+=4)d=f[e],g=f[e+1],a.length==4&&(d=0),f[e]=a[d*4],f[e+1]=a[d*4+1],f[e+2]=a[d*4+2],f[e+3]=a[d*4+3]*(c?g/255:g<10?0:1);return b},Pu:function(b,a,c,
f,g,e,h){var k,v,u;for(u=-1;u<=1;u++)for(v=-1;v<=1;v++)k=(k=b.getQuad(a,c+u,f+v,!0))?b.Kj(k.average):128,g.fillStyle="rgba("+k+",128,0,1)",g.fillRect((v+1)*e,(u+1)*e,e,e);this.Io.blurContext(g,g,e-d(e/10),0,0,h,h,3)},Ct:function(b,a,c,f,d,e){var g=1<<a;d<<=a;f<<=a;return b.getQuads(c+a,f-1,f+g,d-1,d+g,e)}})})(nokia.maps);ovi.provide("nokia.maps.heatmap._TileHashMap");
(function(e){var k=e.heatmap,h=e.geo.mercator,d=e.util.vf,e=Math,c=e.round,g=e.log,b=e.pow,f=k.Ii=new ovi.Class({initialize:function(b,c,f){var d=0;this.Ya=b>30?30:b<0?0:b;this.Cl=f||this.Ya;c==="value"?(this.nn=q,this.Kj=this.qu):(this.nn=a,this.Kj=this.pu);this.Rb=[];this.fd=[];for(d=0;d<=b;d++)this.fd[d]=[],this.Rb[d]=new r;this.Hj=-1/0;this.ph=1/0;this.bj=null},fd:null,Rb:null,Ya:null,addDataPoint:function(a){var b=h.latLngToMapPoint(a.latitude,a.longitude),c=this.Ya,f=b.x>>30-this.Ya,b=b.y>>
30-this.Ya,d,g=this.nn;d=a.value==null?1:a.value;if(d>this.Hj)this.Hj=d,this.bj=this.Hj-this.ph;if(d<this.ph)this.ph=d,this.bj=this.Hj-this.ph;for(;c>=0;){this.fd[c][b]||(this.fd[c][b]=[]);d=this.fd[c][b][f]||(this.fd[c][b][f]=new g);d.addDataPoint(a,this.Ya,c);if(this.Rb[c].minSum>d.sum)this.Rb[c].minSum=d.sum;if(this.Rb[c].maxSum<d.sum)this.Rb[c].maxSum=d.sum;if(this.Rb[c].minAverage>d.average)this.Rb[c].minAverage=d.average;if(this.Rb[c].maxAverage<d.average)this.Rb[c].maxAverage=d.average;c--;
f>>=1;b>>=1}},getQuad:function(a,b,c,f){c=d(c,1<<a);return(quad=(rowInRange=b>=0&&b<=(1<<a)-1)&&this.fd[a]&&this.fd[a][b]&&this.fd[a][b][c]||null)?quad:f&&a>=0?this.getQuad(a-1,b>>1,c>>1,f):quad},getQuads:function(a,b,c,f,d,g){for(var e=f,h=[];b<=c;b++){for(;e<=d;e++)h.push(this.getQuad(a,b,e,g));e=f}return h},clear:function(){f.call(this,this.Ya,this.nn==q?"value":"density",this.Cl)},aw:function(){var a,b,f=this.Rb,d=this.Ya,e=0;b=f[this.Ya].maxSum;for(a=this.Ya;a>=0;a--)if(f[a].maxSum===b)e=a;else break;
b=f[0].maxSum;for(a=0;a<=e;a++)if(b===f[a].maxSum)d=a;else break;if(e>this.Cl)e=this.Cl;a=c(d+(e-d)/2);this.gamma=g(0.5)/g(f[a].maxAverage);this.Aw=d;this.zw=e},Kj:null,pu:function(a){return this.gamma!=null?c(b(a,this.gamma)*255):127},qu:function(a){return this.bj?c((a-this.ph)/this.bj*255):127}}),q=k.Ii.ValueQuad=function(){this.count=this.sum=this.average=0},a,r;q.prototype={addDataPoint:function(a){this.sum+=a.value!=null?a.value:1;this.average=this.sum/++this.count}};a=k.Ii.DensityQuad=function(){this.count=
this.sum=this.average=0};a.prototype={addDataPoint:function(a,c,f){this.count++;this.sum+=a.value||1;this.average=this.sum/b(2,(30-f)*2)}};r=k.Ii.Level=function(){this.minSum=this.minAverage=Number.POSITIVE_INFINITY;this.maxSum=this.maxAverage=Number.NEGATIVE_INFINITY}})(nokia.maps);ovi.provide("nokia.maps.heatmap.Overlay");
(function(e){var k=e.util,h=e.heatmap,d=k.Coroutine,c=h.Ii,g=h.ds,b=e.map.provider.Tile,f=e.dom.Page.browser,q=f.mozilla&&f.fullVersion=="7.0";h.Overlay=new ovi.Class({Extends:e.map.provider.TileProvider,initialize:function(a){e.dom.supportsCanvas||k.Nf("Heat maps are not supported in this environment, due to missing canvas support.");var b=Math,a=a||{};this._super(a);this.height=this.width=256;this.type=this.type||"density";this.sampleDepth=this.sampleDepth==null?4:b.min(b.max(this.sampleDepth,1),
8);this.assumeValues=!!this.assumeValues;this.dataMax=this.dataMax||this.max;this.coarseness=this.coarseness==null?1:b.min(b.max(this.coarseness,0),3);this.opacity=a.opacity||0.8;this.colors=this.colors||g.DEFAULT_COLORS;this.Of=new c(this.max+this.sampleDepth,this.type,this.dataMax);this.Rv=new g(this.width,this.coarseness,this.colors);this.zf=[];this.Ih={};this.Wm(this)},Statics:{TYPE_DENSITY:"density",TYPE_VALUE:"value"},addData:function(a){for(var b=0,c=a.length;b<c;b++)this.Of.addDataPoint(a[b]);
this.type==="density"&&this.Of.aw();this.update()},clear:function(){this.Of.clear();this.update()},create:function(a,c,f,e){var g=a<=this.max&&a>=this.min,h=this.assumeValues,k,q,u=new b(e,0,this);if(this.Of.getQuad(0,0,0)){if(g){if(!h){k=this.Of.getQuads(a,c-1,c+1,f-1,f+1);for(q=k.length;q--&&!h;)k[q]!=null&&(h=!0)}h&&(this.Va[e]=u,this.zf.push({id:e,level:a,row:c,col:f}),d.signal(this.Ih))}}else u.state=!1;u.state=g&&h?void 0:!1;return u},Wm:d.create("nokia.maps.heatmap.Overlay#_paintCo",function(a){for(var a=
a.that,b,c=this.width,f,e,g;f=a.zf.shift();)if(b=this.Va[f.id])if(e=document.createElement("canvas"),e.width=e.height=c,g=e.getContext("2d"),f=a.Rv.paint(a.Of,c,a.sampleDepth,a.dataMax,a.assumeValues,a.type,f.level,f.row,f.col),g.drawImage(f[0],f[1],f[1],f[1],f[1],0,0,c,c),q&&g.drawImage(e,0,0),b.data=e,b.state=!0,this.finishRequest(b.id,b,1),d.shallYield())return d.yield();return d.wait(a.Ih)},{useAnimationFrame:!0},"that")})})(nokia.maps);ovi.provide("nokia.maps.heatmap._packaging.package-heatmap");})();
