(function(){ovi.provide("nokia.maps.routing.WaypointParameterList");
nokia.maps.routing.WaypointParameterList=new ovi.Class({initialize:function(){this.waypointList=[]},addCoordinate:function(e){this.waypointList.push(e)},addPlace:function(e){this.waypointList.push(e)},addLocation:function(e){this.waypointList.push(e)},size:function(){return this.waypointList.length},clear:function(){this.waypointList=[]},toCoordinates:function(){var e=[],k,h,d;k=0;for(h=this.waypointList.length;k<h;k++)d=this.waypointList[k],"latitude"in d&&"longitude"in d?this.Tu(d,e):"locations"in
d?this.Uu(d,e):("displayPosition"in d||"navigationPosition"in d)&&this.Nq(d,e);return e},Tu:function(e,k){k.push(e)},Uu:function(e,k){for(var h=0,d=e.locations.length;h<d;h++)this.Nq(e.locations[h],k)},Nq:function(e,k){e.displayPosition?k.push(e.displayPosition):e.navigationPosition&&k.push(e.navigationPosition)}});ovi.provide("nokia.maps.routing.Maneuver");ovi.provide("nokia.maps.routing.Mode");ovi.provide("nokia.maps.routing.Route");ovi.provide("nokia.maps.routing.RouteLeg");ovi.provide("nokia.maps.routing.RouteSegment");
ovi.provide("nokia.maps.routing.RouteSummary");ovi.provide("nokia.maps.routing.ServiceError");ovi.provide("nokia.maps.routing.Waypoint");ovi.provide("nokia.maps.routing.component.IsolineResultSet");(function(e){e.routing.component.IsolineResultSet=new ovi.Class({initialize:function(k,h){var d=this.container=new e.map.Container,c=h||{},g,b=e.map.Polygon;g=c.brush||{color:"#00F4"};c=c.pen||{strokeColor:"#00F8",lineWidth:5};k&&(o=new b(k,{pen:c,brush:g}),d.objects.add(o))},container:null})})(nokia.maps);
ovi.provide("nokia.maps.routing.navteq.protocol");
nokia.maps.routing.navteq.protocol={Mode:{type:1,transportModes:1,options:1,trafficMode:1},df:function(e){return e.latitude+","+e.longitude},Ru:function(e){for(var k="",h=e.locations,e=0;e<h.length;e++)k+=this.eq(h[e],e);return k},eq:function(e,k){var h="",d,c;(k||0)===0&&e.displayPosition&&(h+=this.df(e.displayPosition));if(d=e.navigationPositions)for(c=0;c<d.length;c++)h+="!"+this.df(d[c]),e.address&&e.address.street&&(h+=";"+encodeURIComponent(e.address.street));else e.navigationPosition?(h+="!"+
this.df(e.navigationPosition),e.address&&e.address.street&&(h+=";"+encodeURIComponent(e.address.street))):throwIllegalArgument("navigation position is not specified in location!");return h}};ovi.provide("nokia.maps.routing.component.ContextMenuHandler");
(function(e){var k=e.config.routing,h=e.map,d=e.routing,c=d.WaypointParameterList,g=k&&k.protocol&&k.protocol.indexOf("62")>0,b={type:"shortest",transportModes:["car"],options:""};e.map.component.ContextMenu.routingHandler=e.routing.component.ContextMenuHandler=function(f,e){function a(){var a=u.nv;a&&x.objects.remove(a)}function k(b,c,d){var r;var q;a();if(d==="finished"&&(r=(q=(b=b.routes[0])&&b.shape,b=q)&&new h.Polyline(b,{pen:{lineWidth:6,strokeColor:"#05BA",lineJoin:"round"},arrows:!0}),b=r))x.objects.add(b),
v.mapDisplay.zoomTo(x.getBoundingBox(),null,"default"),u.nv=b}function l(){var f;a();if(u.nc){f=0;for(var e=u.nc.length;u.nc&&f<e;f++)u.nc[f].set("text",f+1)}u.jh&&u.jh.state==="started"&&u.jh.cancel();if(u.Mf&&u.hf){z=new c;z.addCoordinate(u.Mf.coordinate);for(s=0;u.nc&&s<u.nc.length;s++)z.addCoordinate(u.nc[s].coordinate);z.addCoordinate(u.hf.coordinate);f=u.jh=new d.Manager;f.addObserver("state",k);f.calculateRoute(z,g?[b]:b)}}var m=f.target,p,z,s,v=this,u=v.pv||(v.pv={}),x=u.container||(u.container=
new h.Container);v.mapDisplay.contains(x)||v.mapDisplay.objects.add(x);m instanceof h.Marker&&m.isRoutingMarker?e.addEntry("__i18n_rightClickMenu.removeRoutePoint__",function(){m===u.Mf?u.Mf=null:m===u.hf?u.hf=null:u.nc&&(idx=u.nc.indexOf(m))>=0&&u.nc.splice(idx,1);x.objects.remove(m);l()},1):(p=v.mapDisplay.pixelToGeo(f.displayX,f.displayY),e.addEntry("__i18n_rightClickMenu.setStartWaypoint__",function(){u.Mf?u.Mf.set("coordinate",p):x.objects.add(u.Mf=new h.StandardMarker(p,{text:"A",isRoutingMarker:!0}));
l()},1),e.addEntry("__i18n_rightClickMenu.addWaypoint__",function(){var a=u.nc||(u.nc=new ovi.Array),b=new h.StandardMarker(p,{isRoutingMarker:!0});a.push(b);x.objects.add(b);l()},1),e.addEntry("__i18n_rightClickMenu.setDestinationWaypoint__",function(){u.hf?u.hf.set("coordinate",p):x.objects.add(u.hf=new h.StandardMarker(p,{text:"B",isRoutingMarker:!0}));l()},1))}})(nokia.maps);ovi.provide("nokia.maps.routing.Manager");
(function(e){var k=e.routing.Manager=new ovi.Class({Extends:e.util.OObject,initialize:function(h,d){var c=h||{};this.Ag=d||new e.Config;if(this.constructor===k)return new k.gf(c);this._super(c)},destroy:function(){this.gf=null},Statics:{setDefImpl:function(e){return this.gf||(this.gf=e),!1}}})})(nokia.maps);ovi.provide("nokia.maps.routing.navteq.protocolV72");
nokia.maps.routing.navteq.protocolV72=ovi.extend({},nokia.maps.routing.navteq.protocol,{getCalculateRouteUrl:function(e,k,h,d,c){var g=[],b,f=ovi.type(h)==="array"?h[0]:h,q,h=[];k instanceof nokia.maps.routing.WaypointParameterList||nokia.maps.util.d("The argument in calculateRoute request is illegal");k.size()<2&&nokia.maps.util.d("Less than two waypoints submitted to calculateRoute call");e+="routeattributes=shape&maneuverattributes=all&jsonAttributes=1";for(b in d)e+="&"+b+"="+d[b];d=k.waypointList;
for(k=0;k<d.length;k++)if(b=d[k],"latitude"in b&&"longitude"in b)e+="&waypoint"+k+"=geo!"+this.df(b);else if("locations"in b)e+="&waypoint"+k+"=street!"+this.Ru(b);else if("displayPosition"in b||"navigationPositions"in b||"navigationPosition"in b)e+="&waypoint"+k+"=street!"+this.eq(b);e+="&language="+c;for(q in f)this.Mode[q]||nokia.maps.util.d('the argument "'+q+'" in mode of calculateRoute Request is illegal');f.type&&(g[g.length]=f.type);f.transportModes&&(g[g.length]=f.transportModes.join(","));
f.trafficMode&&(g[g.length]="traffic:"+f.trafficMode);q=f.options||[];ovi.type(q)=="string"&&(q=q.split(","));if(q){for(c=f=0;c<q.length;c++)switch(q[c]){case "avoidTollroad":h[f++]="tollroad:-1";break;case "avoidMotorway":h[f++]="motorway:-1";break;case "avoidBoatFerry":h[f++]="boatFerry:-1";break;case "avoidRailFerry":h[f++]="railFerry:-1";break;case "avoidPublicTransport":h[f++]="publicTransport:-1";break;case "avoidTunnel":h[f++]="tunnel:-1";break;case "avoidDirtRoad":h[f++]="dirtRoad:-1";break;
case "avoidPark":h[f++]="park:-1";break;case "preferHOVLane":h[f++]="HOVLane:1";break;case "avoidStairs":h[f++]="stairs:-1"}g[g.length]=h.join(",")}e+="&mode="+g.join(";");return e}});ovi.provide("nokia.maps.routing.component.RouteResultSet");
(function(e){function k(c,b){return c[b==="walk"?"originalPosition":"mappedPosition"]}var h=e.map,d=h.StandardMarker,c=e.util;e.routing.component.RouteResultSet=new ovi.Class({initialize:function(e,b){var f=(this.container=new h.Container).objects,q=e.waypoints,a=e.mode.transportModes,r;r=e.shape;var l;r&&f.add((new h.Polyline(r,{pen:new c.Pen({strokeColor:"#05E8",lineWidth:7}),arrows:new c.Arrows})).set(b));if(q){r=q.length-1;f.add(new d(k(q[0],a),{text:"A",identifier:"waypoints"}));for(l=1;l<r;l++)f.add(new d(k(q[l],
a),{identifier:"waypoints",pos:l-1}));f.add(new d(k(q[r],a),{text:"B",identifier:"waypoints"}))}}})})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package");ovi.provide("nokia.maps.routing.navteq.Manager");
(function(e){function k(){var b=d.serviceMode,c=nokia.maps.config.routing.baseUrl,f=nokia.maps.config.routing["secure.baseUrl"];b==="cit"&&nokia.maps.config.routing.protocol==="nokia.maps.routing.navteq.protocolV62"&&(b="st");a.setDefaultsNS(p,{baseUrl:c?c.replace("{serviceMode}",b?"."+b:""):"","secure.baseUrl":f?f.replace("{serviceMode}",b?"."+b:""):"","calculateroute.interface":"calculateroute.json"})}var h=e.util,d=h.getRootNameSpace("nokia.maps").Settings,c=h.d,g=e.geo,b=g.BoundingBox,f=g.Coordinate,
q=g.Shape,a=e.Config,r=h.isArray,l=h.services,m=e.net.Request,p="routing",e=nokia.maps.routing.navteq.Manager=new ovi.Class({initialize:function(a,b){this.qk=new m(m.JSONP,{callbackKey:"jsoncallback",autoSkip:!0});this.$u=ovi.buildNS(nokia.maps.config.routing.protocol);this.addObserver("_shapeParsed",this.tr);this._super(a,b)},Extends:nokia.maps.routing.Manager,Statics:{ut:function(){var a={waypoint:"waypoints",leg:"legs",link:"links",maneuver:"maneuvers",feature:"features"};return function(b){for(var c=
[],d="";b;){for(var f in b)if(d=a[f],a[f]?(b[a[f]]=b[f],delete b[f]):f=="_type"?delete b[f]:d=f,r(b[d])){if(f!="Shape"&&f!="TransportModes")for(var e=0;e<b[d].length;e++)c[c.length]=b[d][e]}else typeof b[d]=="object"&&(c[c.length]=b[d]);c.length>0?b=c.pop():(delete c,b=!1)}}}()},state:"initial",state:"initial",routes:[],Fw:"shape",yw:"direction,shape",Ji:{},tr:!1,zm:0,ym:0,getRoutes:function(){return this.routes},getErrorCause:function(){return this.state=="failed"?this.np:null},calculateRoute:function(a,
b){var c=l.addNlpParams(this.$u.getCalculateRouteUrl(l.getBaseURL(this.Ag,p,"calculateroute"),a,b,this.Ji,d.defaultLanguage));this.Kw=c;this.dt=this.qk.send(c,ovi.bind(this,this.calculateRouteCallback));this.set("state","started",!0)},clear:function(){this.routes=[];this.isolines=[];this.set("state","cleared")},metricSystemSetter:function(a){if(a===void 0||a==="imperial"||a==="metric")return a?this.Ji.metricSystem=a:delete this.Ji.metricSystem,a;else delete this.Ji.metricSystem,c("Metric system is invalid")},
calculateRouteCallback:function(a){this.routes=this.ov(a)},cancel:function(){this.qk.cancelAll();this.set("state","cancelled")},tr:function(a,b,c){if(c)a.set("state","finished"),a.set("_shapeParsed",!1),a.zm=0,a.ym=0},ov:function(a){var c=a.id,d=a.response;if(a.timeout)this.np=this.Kq({type:"SystemError",subtype:"Timeout",details:"request times out"}),this.set("state","failed");else if(d.error||d.type&&d.subtype)this.np=this.Kq(d.error||d),this.set("state","failed");else{nokia.maps.routing.navteq.Manager.ut(d);
for(var a=d.response.route,e,g,l,d=0;d<a.length;d++){this.Lq(a[d],c);for(e=0;e<a[d].waypoints.length;e++)this.an(a[d].waypoints[e]);if(a[d].boundingBox)a[d].boundingBox=b.coverAll([new f(a[d].boundingBox.topLeft.latitude,a[d].boundingBox.topLeft.longitude,void 0,!0),new f(a[d].boundingBox.bottomRight.latitude,a[d].boundingBox.bottomRight.longitude,void 0,!0)]);this.ss(a[d]);if(a[d].mode.features){a[d].mode.options=[];for(e=0;e<a[d].mode.features.length;e++)a[d].mode.options.push(this.rt[a[d].mode.features[e].value]);
delete a[d].mode.features}if(a[d].legs)for(e=0;e<a[d].legs.length;e++){this.an(a[d].legs[e].start);this.an(a[d].legs[e].end);for(g=0;g<a[d].legs[e].maneuvers.length;g++)l=a[d].legs[e].maneuvers[g],l.shape&&this.Lq(l,c),l.position=new f(l.position.latitude,l.position.longitude,void 0,!0)}}return a}},ss:function(a){a.getStart=function(){return a.waypoints[0]};a.getDestination=function(){return a.waypoints[a.waypoints.length-1]};a.getManeuvers=function(){for(var b=[],c=0;c<a.legs.length;c++)b=b.concat(a.legs[c].maneuvers);
return b}},an:function(a){a.linkId&&delete a.linkId;a.mappedPosition=new f(a.mappedPosition.latitude,a.mappedPosition.longitude,void 0,!0);a.originalPosition&&(a.originalPosition=new f(a.originalPosition.latitude,a.originalPosition.longitude,void 0,!0))},Lq:function(a,b){var c=this;c.zm++;q.fromLatLngArray(a.shape.join(",").split(","),!1,function(d){c.ym++;if(c.dt==b)a.shape=d,c.zm==c.ym&&c.set("_shapeParsed",!0)})},rt:{tollroad:"avoidTollroad",motorway:"avoidMotorway",boatFerry:"avoidBoatFerry",
railFerry:"avoidRailFerry",publicTransport:"avoidPublicTransport",tunnel:"avoidTunnel",dirtRoad:"avoidDirtRoad",park:"avoidPark",HOVLane:"preferHOVLane",stairs:"avoidStairs"},Kq:function(a){var b=a.details;a.additionalData&&a.additionalData.length&&(b+=" Key: "+a.additionalData[0].key+", Value: "+a.additionalData[0].value);return{type:a.type.charAt(0).toLowerCase()+a.type.substr(1),subtype:a.subtype.charAt(0).toLowerCase()+a.subtype.substr(1),message:b}}});nokia.maps.routing.Manager.setDefImpl(e);
d.addObserver("serviceMode",k);k()})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package-nlp");})();
